### PR TITLE
Add initial explainer page content

### PR DESCRIPTION
**Pull request by pb4pixels**
Latest version of the explainer page content.

- [ ]  Need to add link to API documentation in the API section. 
- [ ] In page navigation / table of contents

### CODE REVIEW

**Comment by Floppy** [comment]
@gtvj should we move this to translations, as you did for the terms page?

**Comment by Floppy** [comment]
Is this one superceded by #170 @gtvj ?

**Comment by symroe** [comment]
@Floppy You might find this method easier to work with:

* https://github.com/DemocracyClub/WhoCanIVoteFor/blob/master/wcivf/apps/core/views.py#L16
* https://github.com/DemocracyClub/WhoCanIVoteFor#translatedtemplateview

`terms.heading.two.fourth` etc is...fragile!

**Comment by gtvj** [comment]
It is. I've ported the content across to the other PR so will close this one.

**Comment by gtvj** [comment]
Thanks for the suggestion @symroe - that looks like a good proposal. I'll have a look into it. 👍🏽

**Pull request closed without merging**
